### ISSUE TITLE
Add tab size field for manual control

### ISSUE THREAD

**Issue by cowgill** [sindresorhus/tab-size-on-github#13] opened 2016-09-28 12:18 UTC
Some people like a 4 tab size. Others like me, prefer 2. This feature would be a nice addition.

[Another extension](https://chrome.google.com/webstore/detail/github-tab-sizer/djpnapkcpjomnkfekaedkigfomiedpjf) already does this (for reference). 

Thanks!

**Comment by sindresorhus** [comment] 2016-09-28 14:55
Duplicate of #9.

**Closed by sindresorhus** 2016-09-28 14:55 UTC
